packages:
  - apps/website
  - packages/sonia-ui
  - packages/sonia-ui-cli
onlyBuiltDependencies:
  - '@parcel/watcher'
overrides:
  '@chakra-ui/react': '^3.30.0'
  '@ark-ui/react': '^5.30.0'
  '@types/react': '^19.2.2'
  '@types/react-dom': '^19.2.0'
